;Remove previous files
RMDir /r "$INSTDIR\boards"
RMDir /r "$INSTDIR\generic"
RMDir /r "$INSTDIR\iconengines"
RMDir /r "$INSTDIR\imageformats"
RMDir /r "$INSTDIR\networkinformation"
RMDir /r "$INSTDIR\platforms"
RMDir /r "$INSTDIR\styles"
RMDir /r "$INSTDIR\tls"
RMDir /r "$INSTDIR\lang"
Delete "$INSTDIR\*.dll"
Delete "$INSTDIR\COPYING"
Delete "$INSTDIR\ReadMe.txt"
Delete "$INSTDIR\README.md"
Delete "$INSTDIR\iQPuzzle.exe"
Delete "$INSTDIR\Uninstall.exe"
