version: '1.4.2-{build}'

skip_commits:
  author: /transifex/

environment:
  matrix:
    - BUILD: mingw64_Qt6
      QTDIR: C:\Qt\6.8\mingw_64
      MINGW_DIR: C:\Qt\Tools\mingw1310_64
      PRO_MAKE: mingw32-make
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2022
    - BUILD: msvc2022_64
      QTDIR: C:\Qt\6.8\msvc2022_64
      PRO_MAKE: nmake
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2022
    - BUILD: mingw32_reactos
      QTDIR: C:\Qt\5.6\mingw49_32
      MINGW_DIR: C:\Qt\Tools\mingw492_32
      PRO_MAKE: mingw32-make
      DEPLOYQT_FLAGS: --no-angle
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015

install:
  - set PATH=%QTDIR%\bin;%MINGW_DIR%\bin;%PATH%
  - if %BUILD%==msvc2022_64 call "C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Auxiliary\Build\vcvarsall.bat" amd64

configuration: Release

before_build:
  - qmake iqpuzzle.pro
  - lrelease iqpuzzle.pro

build_script:
  - '%PRO_MAKE%'

after_build:
  - mkdir iQPuzzle\boards
  - copy release\iQPuzzle.exe iQPuzzle\iQPuzzle.exe
  - windeployqt --release --no-translations --no-opengl-sw --no-network %DEPLOYQT_FLAGS% iQPuzzle\iQPuzzle.exe
  - copy COPYING iQPuzzle\
  - curl -fsSL -o ReadMe.txt https://raw.githubusercontent.com/ElTh0r0/iqpuzzle/packaging/Windows/ReadMe.txt
  - copy ReadMe.txt iQPuzzle\
  - xcopy /i /e /s data\boards\* iQPuzzle\boards\
  - 7z a iQPuzzle-%APPVEYOR_BUILD_VERSION%-Windows_%BUILD%.zip .\iQPuzzle\
  - curl -fsSL -o iqpuzzle.nsi https://raw.githubusercontent.com/ElTh0r0/iqpuzzle/packaging/Windows/iqpuzzle.nsi
  - curl -fsSL -o removeprevious.nsh https://raw.githubusercontent.com/ElTh0r0/iqpuzzle/packaging/Windows/removeprevious.nsh
  - curl -fsSL -o iqpuzzle.ico https://raw.githubusercontent.com/ElTh0r0/iqpuzzle/packaging/Windows/iqpuzzle.ico
  - makensis iqpuzzle.nsi
  - ren iQPuzzle_Installer.exe iQPuzzle-%APPVEYOR_BUILD_VERSION%-Windows_%BUILD%.exe

artifacts:
  - path: iQPuzzle-%APPVEYOR_BUILD_VERSION%-Windows_%BUILD%.zip
  - path: iQPuzzle-%APPVEYOR_BUILD_VERSION%-Windows_%BUILD%.exe
