version: '1.0.6-{build}'

environment:
  QTDIR: C:\Qt\5.8\mingw53_32
  MINGW_DIR: C:\Qt\Tools\mingw530_32
  
install:
  - set PATH=%QTDIR%\bin;%MINGW_DIR%\bin;%PATH%

configuration: Release

before_build:
  - qmake iqpuzzle.pro
  - lrelease lang/*.ts

build_script:
  - mingw32-make

after_build:
  - mkdir iQPuzzle\lang
  - copy release\iQPuzzle.exe iQPuzzle\iQPuzzle.exe
  - windeployqt --release --no-translations --no-angle --no-opengl-sw iQPuzzle/iQPuzzle.exe
  - copy COPYING iQPuzzle\
  - copy README.md iQPuzzle\
  - copy lang\*.qm iQPuzzle\lang\
  - copy data\boards iqPuzzle\
  - 7z a iQPuzzle-$(APPVEYOR_BUILD_VERSION)-Windows.zip .\iQPuzzle\

artifacts:
  - path: iQPuzzle-$(APPVEYOR_BUILD_VERSION)-Windows.zip
