environment:
  APPVERSION: 1.0.6
  QTDIR: C:\Qt\5.8\mingw53_32
  MINGW_DIR: C:\Qt\Tools\mingw530_32

version: '$(APPVERSION)-{build}'
  
install:
  - set PATH=%QTDIR%\bin;%MINGW_DIR%\bin;%PATH%

configuration: Release

before_build:
  - qmake iqpuzzle.pro

build_script:
  - mingw32-make

after_build:
  - mkdir iQPuzzle-$(APPVERSION)
  - copy release\iQPuzzle.exe iQPuzzle-$(APPVERSION)\iQPuzzle.exe
  - windeployqt --release --no-translations --no-angle --no-opengl-sw iQPuzzle-$(APPVERSION)/iQPuzzle.exe
  - 7z a iQPuzzle-$(APPVERSION)-Windows.zip .\iQPuzzle-$(APPVERSION)\

artifacts:
  - path: iQPuzzle-$(APPVEYOR_BUILD_VERSION)-Windows.zip
