version: '1.1.0-{build}'

environment:
  matrix:
    - BUILD: mingw32 
      QTDIR: C:\Qt\5.9.2\mingw53_32
      MINGW_DIR: C:\Qt\Tools\mingw530_32
      PRO_MAKE: mingw32-make
    - BUILD: msvc2015_64
      QTDIR: C:\Qt\5.9.2\msvc2015_64
      PRO_MAKE: nmake
  
install:
  - set PATH=%QTDIR%\bin;%MINGW_DIR%\bin;%PATH%
  - if %BUILD%==msvc2015_64 call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" amd64

configuration: Release

before_build:
  - qmake iqpuzzle.pro
  - lrelease iqpuzzle.pro

build_script:
  - '%PRO_MAKE%'

after_build:
  - mkdir iQPuzzle\boards
  - copy release\iQPuzzle.exe iQPuzzle\iQPuzzle.exe
  - windeployqt --release --no-translations --no-angle --no-opengl-sw iQPuzzle\iQPuzzle.exe
  - copy COPYING iQPuzzle\
  - copy README.md iQPuzzle\
  - xcopy /i /e /s data\boards\* iQPuzzle\boards\
  - 7z a iQPuzzle-%APPVEYOR_BUILD_VERSION%-Windows_%BUILD%.zip .\iQPuzzle\

artifacts:
  - path: iQPuzzle-%APPVEYOR_BUILD_VERSION%-Windows_%BUILD%.zip
