version: '1.0.6'

environment:
  QTDIR: C:\Qt\5.8\mingw53_32
  MINGW_DIR: C:\Qt\Tools\mingw530_32

install:
  - set PATH=%QTDIR%\bin;%MINGW_DIR%\bin;%PATH%

configuration: Release

before_build:
  - qmake iqpuzzle.pro

build_script:
  - mingw32-make

after_build:
  - mkdir iQPuzzle-%version%
  - copy release\iQPuzzle.exe iQPuzzle-%version%\iQPuzzle.exe
  - windeployqt --release --no-translations --no-angle --no-opengl-sw iQPuzzle-%version%/iQPuzzle.exe
  - 7z a iQPuzzle-%version%-Windows.zip .\iQPuzzle-%version%\

artifacts:
  - path: iQPuzzle-$(version)-Windows.zip
