environment:
  QTDIR: C:\Qt\5.8\mingw53_32

install:
  - set PATH=%QTDIR%\bin;%PATH%

before_build:
  - qmake iqpuzzle.pro

configuration:
  - Release
  
after_build:
  - mkdir deploy
  - copy release\iQPuzzle.exe deploy\iQPuzzle.exe
  - windeployqt --release --no-translations --no-angle --no-opengl-sw deploy/iQPuzzle.exe
  - 7z a iqpuzzle.zip .\deploy\*

artifacts:
  - path: iqpuzzle.zip
