environment:
  QTDIR: C:\Qt\5.8\mingw53_32
  MINGW_DIR: C:\Qt\Tools\mingw530_32 

install:
  - set PATH=%QTDIR%\bin;%MINGW_DIR%\bin;%PATH%
  
configuration: Release

before_build:
  - qmake iqpuzzle.pro

build_script:
  - mingw32-make

after_build:
  - windeployqt iQPuzzle.exe
  - 7z a iqpuzzle.zip *

artifacts:
  - path: iqpuzzle.zip
    name: iQPuzzle
