'\" t
.\" ** The above line should force tbl to be a preprocessor **
.\" Man page for iQPuzzle
.\"
.\" Copyright (C), 2014, Thorsten Roth
.\"
.\" You may distribute under the terms of the GNU General Public
.\" License as specified in the file COPYING that comes with the man
.\" distribution.
.\"
.\" Sat Jul  19 16:02:29 CEST 2014  ElThoro <elthoro@gmx.de>
.\"
.TH IQPUZZLE 1 "2014-07-19" "Thorsten Roth" "iQPuzzle Handbuchseite"
.SH NAME
iQPuzzle \- Ein Pentomino Puzzle
.SH SYNOPSIS
\fBiqpuzzle\fP [\fIOption\fP] oder [\fIPuzzle\-Datei\fP]
.SH BESCHREIBUNG
\fPiqpuzzle\fP ist ein kurzweiliges und anspruchsvolles Pentomino Puzzle.
.SS Optionen
.TP
\fB\-\-version\fP
Versionsnummer ausgeben.
.SH DATEIEN
.TP
.I /usr/share/iqpuzzle/boards
Puzzle\-Dateien
.SH FEHLER
Launchpad Bugtracker:

https://bugs.launchpad.net/iqpuzzle
