'\" t
.\" ** The above line should force tbl to be a preprocessor **
.\" Man page for iQPuzzle
.\"
.\" Copyright (C), 2018, Thorsten Roth
.\"
.\" You may distribute under the terms of the GNU General Public
.\" License as specified in the file COPYING that comes with the man
.\" distribution.
.\"
.\" Mon Jan  01 19:33:00 CEST 2018  ElThoro <elthoro@gmx.de>
.\"
.TH IQPUZZLE 6 "2018-01-01" "Thorsten Roth" "iQPuzzle Handbuchseite"
.SH NAME
iQPuzzle \- Ein Pentomino Puzzle
.SH SYNOPSIS
\fBiqpuzzle\fP [\fI\-v, \-\-version\fP] oder [\fIDatei\fP]
.SH BESCHREIBUNG
\fPiqpuzzle\fP ist ein kurzweiliges und anspruchsvolles Pentomino Puzzle.
.SS Optionen
.TP
\fB\-v, \-\-version\fP
Versionsnummer ausgeben.
.TP
\fBDatei\fP
Zu \(:offnendes Spielfeld (.conf) oder gespeichertes Spiel (.iqsav).
.SH DATEIEN
.TP
.I /usr/share/iqpuzzle/boards
Puzzle\-Dateien
.SH FEHLER
GitHub Bugtracker:

https://github.com/ElTh0r0/iqpuzzle/issues
