'\" t
.\" ** The above line should force tbl to be a preprocessor **
.\" Man page for iQPuzlle
.\"
.\" Copyright (C), 2014, Thorsten Roth
.\"
.\" You may distribute under the terms of the GNU General Public
.\" License as specified in the file COPYING that comes with the man
.\" distribution.
.\"
.\" Sat Jul  19 16:02:29 CEST 2014  ElThoro <elthoro@gmx.de>
.\"
.TH IQPUZZLE 1 "2014-07-19" "Thorsten Roth" "iQPuzzle Manual"
.SH NAME
iQPuzzle \- Pentomino Puzzle
.SH SYNOPSIS
\fBiqpuzzle\fP [\fIOption\fP] or [\fIPuzzle file\fP]
.SH DESCRIPTION
\fPiqpuzzle\fP is a diverting and challenging pentomino puzzle.
.SS Options
.TP
\fB\-\-version\fP
Print out version.
.SH FILES
.TP
.I /usr/share/games/iqpuzzle/boards
Puzzle files
.SH BUGS
Launchpad bug tracker:

https://bugs.launchpad.net/iqpuzzle
